name: "Truth in Fandom"
description: |
  One of your friends, a hardcore Star Wars fan, told you to checkout his site <link>. He said he's got the scoop on the new movie. Maybe you can find some truth in his website after all.
flag: "MCA-57412B01"